name: Template Cleanup
on:
  push:
    branches: [main]

jobs:

  # Run a cleaning process only if the workflow is triggered by the non-"intellij-platform-plugin-template" repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'Android-Starter'
    permissions:
      contents: write
    steps:

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Cleanup project
      - name: Cleanup
        run: |
          set -e  # 遇到错误立即退出
          export LC_CTYPE=C
          export LANG=C

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo $ACTOR | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.$SAFE_ACTOR.$SAFE_NAME"

          echo "处理变量:"
          echo "NAME: $NAME"
          echo "ACTOR: $ACTOR"
          echo "SAFE_NAME: $SAFE_NAME"
          echo "SAFE_ACTOR: $SAFE_ACTOR"
          echo "GROUP: $GROUP"

          # Replace placeholders in the template-cleanup files
          echo "替换模板文件中的占位符..."
          if [ -d ".github/template-cleanup" ]; then
            sed -i.bak "s/%NAME%/$NAME/g" .github/template-cleanup/*
            sed -i.bak "s/%REPOSITORY%/${GITHUB_REPOSITORY/\//\\/}/g" .github/template-cleanup/*
            sed -i.bak "s/%GROUP%/$GROUP/g" .github/template-cleanup/*
          fi

          # Replace template package name in project files with $GROUP
          echo "替换源文件中的包名..."
          find app/src -type f -name "*.kt" -o -name "*.java" -o -name "*.xml" | while read file; do
            echo "处理文件: $file"
            sed -i.bak "s|com.mcallzbl.android_starter|$GROUP|g" "$file"
          done

          # Move content
          echo "创建新的包名目录结构..."
          mkdir -p "app/src/main/java/${GROUP//.//}"
          mkdir -p "app/src/test/java/${GROUP//.//}"
          mkdir -p "app/src/androidTest/java/${GROUP//.//}"

          echo "移动文件到新的包名目录..."
          if [ -d "app/src/main/java/com/mcallzbl/android_starter" ]; then
            cp -R app/src/main/java/com/mcallzbl/android_starter/* "app/src/main/java/${GROUP//.//}/" || echo "警告: 主源代码目录复制失败"
          fi
          
          if [ -d "app/src/test/java/com/mcallzbl/android_starter" ]; then
            cp -R app/src/test/java/com/mcallzbl/android_starter/* "app/src/test/java/${GROUP//.//}/" || echo "警告: 测试代码目录复制失败"
          fi
          
          if [ -d "app/src/androidTest/java/com/mcallzbl/android_starter" ]; then
            cp -R app/src/androidTest/java/com/mcallzbl/android_starter/* "app/src/androidTest/java/${GROUP//.//}/" || echo "警告: Android测试代码目录复制失败"
          fi

          # Verify new directories
          echo "验证新目录结构..."
          if [ ! -d "app/src/main/java/${GROUP//.//}" ]; then
            echo "错误: 新的主源代码目录未成功创建"
            exit 1
          fi

          # Cleanup
          echo "清理旧文件和目录..."
          rm -rf \
            .github/ISSUE_TEMPLATE \
            .github/readme \
            .github/template-cleanup \
            .github/workflows/template-cleanup.yml \
            .github/workflows/template-verify.yml \
            .idea/icon.png \
            app/src/main/java/com/mcallzbl/android_starter \
            app/src/test/java/com/mcallzbl/android_starter \
            app/src/androidTest/java/com/mcallzbl/android_starter \
            CODE_OF_CONDUCT.md \
            LICENSE

          # Cleanup backup files
          echo "清理临时文件..."
          find . -name "*.bak" -type f -delete

          echo "模板清理完成"

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}